services:
  backend:
    image: ghcr.io/ammar-devops/ecommerce-backend:latest

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

    restart: unless-stopped

    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: ghcr.io/ammar-devops/ecommerce-frontend:latest

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: ammar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres-data:
